module.exports = {
  someSidebar: {
    "Getting Started": [
      "embeds-introduction",
      "embeds-configurator",
      "embeds-modular",
      "embeds-utils",
      "events",
      "localization",
      "custom-translations",
      "custom-css"
    ],
    "Authentication API": [
      "auth-introduction",
      "auth-auth",
      "auth-user",
      "auth-forgot-password",
    ],
    Libraries: ["library-html-client"],
    Examples: ["guides-modular"],
    Specification: [
      {
        type: "link",
        label: "API Reference",
        href: "/api-reference",
      },
      {
        type: 'autogenerated',
        dirName: 'web',
      }
    ],
  },
}
