module.exports = {
  someSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: true,
      items: [
        "embeds-introduction",
        "embeds-configurator",
        "embed-options",
        "embeds-modular",
        "embeds-utils",
        "events",
        "localization",
        "custom-translations",
        "custom-css"
      ]
    },
    {
      type: 'category',
      label: 'Authentication API',
      collapsible: true,
      collapsed: true,
      items: [
        "auth-introduction",
        "auth-auth",
        "auth-user",
        "auth-forgot-password",
      ]
    },
    {
      type: 'category',
      label: 'Libraries',
      collapsible: true,
      collapsed: true,
      items: [
        "library-html-client"
      ]
    },
    {
      type: 'category',
      label: 'Examples',
      collapsible: true,
      collapsed: true,
      items: [
        "guides-modular"
      ]
    },
    {
      type: 'autogenerated',
      dirName: 'web'
    },
    {
      type: "link",
      label: "API Reference",
      href: "/api-reference",
    }
  ]
}
